
clean:
	make -C 4.1.2.cdd-template clean
	make -C 4.1.3.char-memory clean
	make -C 4.1.4.reg-chrdev clean
	make -C 4.1.5.dynamic-cdd clean
	make -C 4.1.6.cdf-auto  clean
	make -C 4.1.7.kernel_panic clean
	make -C 4.1.8.multiple-cdd clean

