all: thread1 thread2 thread3 
#all: thread1 thread2 
#CFLAGS=-D_REENTRANT
#LDFLAGS=-lpthread

thread1: 
	gcc thread1.c -o thread1 -lpthread
thread2: 
	gcc thread2.c -o thread2 -lpthread
thread3: 
	gcc thread3.c -o thread3 -lpthread
clean:
	rm -f thread1 thread2 thread3 


