
Introduction  to CrashDump/CoreDump:
-----------------------------------
Whenever an application crashes, the operating system can store (or even send) a crash report.
On Linux, whenever an app crashes (most commonly by a segmentation fault, i.e. when accessing a bad pointer/memory), it has the option of generating a core dump.

A core dump is a file containing a process's address space (memory) when the process terminates unexpectedly.
Core dumps may be produced on-demand (such as by a debugger), or automatically upon termination.
Core dumps are triggered by the kernel in response to program crashes, and may be passed to a helper program (such as systemd-coredump) for further processing.

We can use the core dump to diagnose and debug our computer programs by loading the core file into a debugger along with the executable file (for symbols and other debugging information).

What Information coredump contain:
---------------------------------
It also contains a snapshot of all the virtual memory areas accessed by your app, so yes, there can be confidential information stored in a core dump so be careful who you give it to.

**************************************************************************************************************
                                                Coredump @ userspace
**************************************************************************************************************
How to enable coredump:
----------------------
You can check whether core dump files are enabled with the following command:
$ ulimit -c

By default core dump files are disabled, in which case this command will return 0. To enable core dump files, use the following command:
$ ulimit -c unlimited

$ ls -la /proc/sys/kernel/core*
-rw-r--r--. 1 root root 0 Aug 28 23:53 core_pattern
-rw-r--r--. 1 root root 0 Aug 28 16:12 core_pipe_limit
-rw-r--r--. 1 root root 0 Aug 28 23:53 core_uses_pid

$ cat /proc/sys/kernel/core_pattern
|/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e

Note that the first character of the pattern is a "|", the kernel will treat the rest of the pattern as a command to run. The core dump will be written to the standard input of that program instead of to a file.

We need to change the line of the core_pattern to "core".
$ sudo bash -c 'echo core.%e.%p > /proc/sys/kernel/core_pattern'
$ cat /proc/sys/kernel/core_pattern
core.%e.%p

In the setting, %e is for executable file name and %p is for pid.

$ gcc -g error.c -o error
$ ulimit -c unlimited
$ ./error
Segmentation fault (core dumped)
$ ls
core.error.3209 error error.c


Analyzing Core File:
-------------------
gdb <executable> <core-file>

$ gdb ./error core.error.4981
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
[New LWP 4981]
Core was generated by `./error'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004004fd in fun () at error.c:5
5           *ptr = 7;
(gdb)

It indicates the line 5 has an issue.
We can use backtrace to list the call stacks that had been made when the program crashed:
(gdb) bt
#0  0x00000000004004fd in fun () at error.c:5
#1  0x0000000000400513 in main () at error.c:10
(gdb) up
#1  0x0000000000400513 in main () at error.c:10
10          fun();
(gdb) down
#0  0x00000000004004fd in fun () at error.c:5
5           *ptr = 7;

------------------------------------------------------------------------------------------------------------------
