# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 3

SIMPLE=write1 read1 open1
COPY=copy_byte copy_block copy_stdio
FILE=lseek stat

ALL= $(SIMPLE) $(COPY) $(FILE) 

all: $(ALL)

clean:
	@rm -f $(ALL) file.out records.dat *~
